runmode = "dev" # dev  production
serviceName="basesvc"

#后端地址
httpPort=8080
pprofPort=8180
grpcPort =8280

[grpcdepends]
  momentdb="127.0.0.1:8082"
  imapigatewayserver = "192.200.1.199:18999"
#文件上传配置
[uploader]
    mainland = ["http://47.112.162.185:9094"]   #大陆上传
    abroad = ["http://beta.colorchat.me"]    #非大陆

 [logs]
filePath="./" #文件目录 结尾带/
level=-1  #日志等级 	-1 debug  ~  5 fatal
#彩聊机器人
[robot]
endpoint = "http://106.75.154.34:15423"
token ="1300002019:3Xh4MKR0dt6bfwoWBY6cbM24"
roomType = 3 #1 是用户 3是群
roomID = 1400269991 # 用ID 或者群ID