// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infoserver/publiccontact.proto

package infoserver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqUpdateMoments struct {
	UserId               []int32  `protobuf:"varint,1,rep,packed,name=userId,proto3" json:"userId,omitempty"`
	SelfId               int32    `protobuf:"varint,2,opt,name=selfId,proto3" json:"selfId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdateMoments) Reset()         { *m = ReqUpdateMoments{} }
func (m *ReqUpdateMoments) String() string { return proto.CompactTextString(m) }
func (*ReqUpdateMoments) ProtoMessage()    {}
func (*ReqUpdateMoments) Descriptor() ([]byte, []int) {
	return fileDescriptor_33e0b51cdca74a57, []int{0}
}

func (m *ReqUpdateMoments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdateMoments.Unmarshal(m, b)
}
func (m *ReqUpdateMoments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdateMoments.Marshal(b, m, deterministic)
}
func (m *ReqUpdateMoments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdateMoments.Merge(m, src)
}
func (m *ReqUpdateMoments) XXX_Size() int {
	return xxx_messageInfo_ReqUpdateMoments.Size(m)
}
func (m *ReqUpdateMoments) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdateMoments.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdateMoments proto.InternalMessageInfo

func (m *ReqUpdateMoments) GetUserId() []int32 {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ReqUpdateMoments) GetSelfId() int32 {
	if m != nil {
		return m.SelfId
	}
	return 0
}

type ResUpdateMoments struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResUpdateMoments) Reset()         { *m = ResUpdateMoments{} }
func (m *ResUpdateMoments) String() string { return proto.CompactTextString(m) }
func (*ResUpdateMoments) ProtoMessage()    {}
func (*ResUpdateMoments) Descriptor() ([]byte, []int) {
	return fileDescriptor_33e0b51cdca74a57, []int{1}
}

func (m *ResUpdateMoments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResUpdateMoments.Unmarshal(m, b)
}
func (m *ResUpdateMoments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResUpdateMoments.Marshal(b, m, deterministic)
}
func (m *ResUpdateMoments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResUpdateMoments.Merge(m, src)
}
func (m *ResUpdateMoments) XXX_Size() int {
	return xxx_messageInfo_ResUpdateMoments.Size(m)
}
func (m *ResUpdateMoments) XXX_DiscardUnknown() {
	xxx_messageInfo_ResUpdateMoments.DiscardUnknown(m)
}

var xxx_messageInfo_ResUpdateMoments proto.InternalMessageInfo

func (m *ResUpdateMoments) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResUpdateMoments) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqUpdateMoments)(nil), "infoserver.ReqUpdateMoments")
	proto.RegisterType((*ResUpdateMoments)(nil), "infoserver.ResUpdateMoments")
}

func init() { proto.RegisterFile("infoserver/publiccontact.proto", fileDescriptor_33e0b51cdca74a57) }

var fileDescriptor_33e0b51cdca74a57 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcb, 0xcc, 0x4b, 0xcb,
	0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2f, 0x28, 0x4d, 0xca, 0xc9, 0x4c, 0x4e, 0xce, 0xcf,
	0x2b, 0x49, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0xc8, 0x2b, 0x39,
	0x71, 0x09, 0x04, 0xa5, 0x16, 0x86, 0x16, 0xa4, 0x24, 0x96, 0xa4, 0xfa, 0xe6, 0xe7, 0xa6, 0xe6,
	0x95, 0x14, 0x0b, 0x89, 0x71, 0xb1, 0x95, 0x16, 0xa7, 0x16, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30,
	0x6b, 0xb0, 0x06, 0x41, 0x79, 0x20, 0xf1, 0xe2, 0xd4, 0x9c, 0x34, 0xcf, 0x14, 0x09, 0x26, 0x05,
	0x46, 0x90, 0x38, 0x84, 0xa7, 0x64, 0x01, 0x32, 0xa3, 0x18, 0xd5, 0x0c, 0x21, 0x2e, 0x96, 0xe4,
	0xfc, 0x94, 0x54, 0x09, 0x46, 0xb0, 0x4a, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0x39, 0xb7, 0x38, 0x1d,
	0xac, 0x99, 0x33, 0x08, 0xc4, 0x34, 0x4a, 0xe6, 0x12, 0x72, 0x86, 0x38, 0x2d, 0xa0, 0xb4, 0x38,
	0x23, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x97, 0x8b, 0x17, 0xd5, 0x30, 0x19, 0x3d,
	0x84, 0x8b, 0xf5, 0xd0, 0x9d, 0x2b, 0x85, 0x26, 0x8b, 0xea, 0x10, 0x25, 0x86, 0x24, 0x36, 0xb0,
	0xaf, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xc1, 0x40, 0xf4, 0x17, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactPushServiceClient is the client API for ContactPushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactPushServiceClient interface {
	//更新自己朋友的未读状态
	UpdateMoments(ctx context.Context, in *ReqUpdateMoments, opts ...grpc.CallOption) (*ResUpdateMoments, error)
}

type contactPushServiceClient struct {
	cc *grpc.ClientConn
}

func NewContactPushServiceClient(cc *grpc.ClientConn) ContactPushServiceClient {
	return &contactPushServiceClient{cc}
}

func (c *contactPushServiceClient) UpdateMoments(ctx context.Context, in *ReqUpdateMoments, opts ...grpc.CallOption) (*ResUpdateMoments, error) {
	out := new(ResUpdateMoments)
	err := c.cc.Invoke(ctx, "/infoserver.ContactPushService/UpdateMoments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactPushServiceServer is the server API for ContactPushService service.
type ContactPushServiceServer interface {
	//更新自己朋友的未读状态
	UpdateMoments(context.Context, *ReqUpdateMoments) (*ResUpdateMoments, error)
}

// UnimplementedContactPushServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContactPushServiceServer struct {
}

func (*UnimplementedContactPushServiceServer) UpdateMoments(ctx context.Context, req *ReqUpdateMoments) (*ResUpdateMoments, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMoments not implemented")
}

func RegisterContactPushServiceServer(s *grpc.Server, srv ContactPushServiceServer) {
	s.RegisterService(&_ContactPushService_serviceDesc, srv)
}

func _ContactPushService_UpdateMoments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqUpdateMoments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactPushServiceServer).UpdateMoments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infoserver.ContactPushService/UpdateMoments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactPushServiceServer).UpdateMoments(ctx, req.(*ReqUpdateMoments))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactPushService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infoserver.ContactPushService",
	HandlerType: (*ContactPushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateMoments",
			Handler:    _ContactPushService_UpdateMoments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infoserver/publiccontact.proto",
}
